name = "cloudflare-worker"
account_id = "043c7e1ef0cd2d81046911bc6904faa1"
workers_dev = true
compatibility_date = "2024-03-15"

[[kv_namespaces]]
binding = "FLAG_CACHE"
id = "7de62555484f4df7aa9e7d8148f91fd7"

# Add this line to specify the entry-point file
main = "serverCloudwareWorker.ts"
